server:
  port: 7002
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/,http://127.0.0.1:8080/eureka/
spring:
  application:
    name: serviceconsumer
feign:
  hystrix:
    #开启feign的hystrix支持,默认是false
    enabled: true